### ISSUE TITLE
Upstream all of the patches for llvm-8.0svn support

### ISSUE THREAD

**Issue by dylanmckay** [avr-rust/rust#116]
In #115, the version of Rust and LLVM is being updated.

A few patches were cherry-picked into the LLVM fork.

These should be upstreamed.

Here is a full list.

- [x] avr-rust/rust#37: DREGS_WITHOUT_Z
- [ ] avr-rust/rust#92: ret struct
- [x] avr-rust/rust#112: extra op
- [x] avr-rust/rust#117 " Can't compile when using a workspace"
- [ ] external author [D53106](https://reviews.llvm.org/D53106) [SelectionDAG] Fix behavior topological ordering with regards to glued nodes.
- [x]  external author [D53485](https://reviews.llvm.org/D53485) [ScheduleDAGRRList] Do not preschedule the node has ADJCALLSTACKDOWN parent

**Comment by dylanmckay** [comment]
Upstreamed #37 in [r346114](https://github.com/llvm-mirror/llvm/commit/9de46729ce2fb4bf4b2a19b7b387898f256d827f).

Also raised [LLVM bug PR39553](https://bugs.llvm.org/show_bug.cgi?id=39553) to track the workaround and a proper fix.

**Comment by dylanmckay** [comment]
Upstreamed #112 in [r346117](https://github.com/llvm-mirror/llvm/commit/2674d3c5ccb3b57fac1dd38b396bf9d1245bbf60).

Also raised [LLVM bug PR39554](https://bugs.llvm.org/show_bug.cgi?id=39554) to track writing of proper unit tests for `FRMIDX` expansion.

**Comment by dylanmckay** [comment]
Upstream #117 in [r349469](http://llvm.org/viewvc/llvm-project?view=revision&revision=349469)

**Comment by dylanmckay** [comment]
https://reviews.llvm.org/D53485 has recently landed
